# Identify the 

name: Publish Docker image

on:
  push:
    branches:
      - feature-*
      - feature/*

jobs:
  check_changes:
    name: List the paths where change were done
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Check out the repo
        run: python3 --version

      - name: List changed folders
        run : git diff-tree --no-commit-id --name-only -r $GITHUB_SHA

      - name: List changed folders
        run : python3 .github/scripts/list_changed_folders.py
